name: Open new issue

on: workflow_dispatch

jobs:

  open-new-issue:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "${{ github.actor }} triggered the creation of this issue."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
